name: etido
description: Etika Todo Sample Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  get_storage: ^2.0.3
  flutter_slidable: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.1
  firebase_analytics: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true